name: cwLogsSystem_src
main: BeyCoder\LogsSystem
author: BeyCoder
version: "1.0"
load: POSTWORLD
api:
  - 2.0.0
  - 3.0.0

commands:
  log:
    default: true

permissions:
  api.logger:
    description: "Включение режима логов"
  api.logger.moder:
    description: "Игнорирование логирования для модераторов"